/*
 * Copyright 2026 Franz Schöning
 * Project: https://www.zeroz4j.com
 * Author: Franz Schöning - Principal Enterprise Architect (https://www.franzschoning.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.zeroz4j.api;

import java.nio.ByteBuffer;
import java.nio.charset.StandardCharsets;
import java.time.Instant;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Collections;
import java.util.IdentityHashMap;
import java.util.Set;
import java.util.UUID;

/**
 * Handles binary serialization and deserialization for supported RPC primitive types,
 * collection structures, and custom binary packable classes.
 *
 * <p><b>AI Agent Execution Notes:</b></p>
 * <ul>
 *   <li><b>Type Tag Encoding:</b> Every serialized payload begins with a 1-byte header tag (0x00 to 0x21)
 *       identifying the data type (Primitives, String, Object, List, Map, Set, Byte Array, Reference, UUID, Instant, Enum).</li>
 *   <li><b>Cycle &amp; Reference Detection:</b> Uses a {@link ThreadLocal} set of object identities to detect cyclic graphs
 *       and duplicate instances. Serializes subsequent occurrences of an object as a lightweight reference tag
 *       ({@link #TAG_REF}) containing only the object ID string generated by {@link ObjectMapper}.</li>
 *   <li><b>State Mutations:</b> Mutates the target {@link ByteBuffer} or {@link GrowableBuffer} position. When deserializing,
 *       instantiates objects via {@link BinaryRegistry} and registers them with {@link ObjectMapper}.</li>
 *   <li><b>Dependencies:</b> Relies on {@link BinaryRegistry} for generated serializer delegates/factories and
 *       {@link ObjectMapper} for reference ID tracking.</li>
 * </ul>
 */
public class BinarySerializer {
    /** Tag byte indicating a {@code null} reference (0x00). No payload bytes follow. */
    public static final byte TAG_NULL = 0x00;
    /** Tag byte indicating a 4-byte signed integer (0x01). */
    public static final byte TAG_INT = 0x01;
    /** Tag byte indicating an 8-byte signed long integer (0x02). */
    public static final byte TAG_LONG = 0x02;
    /** Tag byte indicating an 8-byte double precision float (0x03). */
    public static final byte TAG_DOUBLE = 0x03;
    /** Tag byte indicating a 4-byte single precision float (0x04). */
    public static final byte TAG_FLOAT = 0x04;
    /** Tag byte indicating a 1-byte boolean flag (0x05; 0 for false, 1 for true). */
    public static final byte TAG_BOOLEAN = 0x05;
    /** Tag byte indicating a UTF-8 encoded String (0x06) prefixed with a 4-byte length. */
    public static final byte TAG_STRING = 0x06;
    /** Tag byte indicating a full complex object instance (0x07) with reference ID, class FQCN, and field payload. */
    public static final byte TAG_OBJECT = 0x07;
    /** Tag byte indicating a 2-byte signed short integer (0x08). */
    public static final byte TAG_SHORT = 0x08;
    /** Tag byte indicating a single byte value (0x09). */
    public static final byte TAG_BYTE = 0x09;
    /** Tag byte indicating a 2-byte character value (0x0A). */
    public static final byte TAG_CHAR = 0x0A;
    /** Tag byte indicating a List (0x0B) prefixed with a 4-byte element count. */
    public static final byte TAG_LIST = 0x0B;
    /** Tag byte indicating a Map (0x0C) prefixed with a 4-byte entry count. */
    public static final byte TAG_MAP = 0x0C;
    /** Tag byte indicating a raw byte array (0x0D) prefixed with a 4-byte length. */
    public static final byte TAG_BYTE_ARRAY = 0x0D;
    /** Tag byte indicating an existing object reference (0x0E) containing only its string ID. */
    public static final byte TAG_REF = 0x0E;
    /**
     * Tag byte indicating a {@link java.util.UUID} (0x0F): the canonical 36-char string form
     * (via {@link java.util.UUID#toString()} / {@link java.util.UUID#fromString(String)}).
     * String form is used rather than two longs because TeaVM does not emulate
     * {@code UUID.getMostSignificantBits()} or {@code new UUID(long, long)}, so this keeps the
     * same code linking on both the JVM server and the Wasm browser client.
     */
    public static final byte TAG_UUID = 0x0F;
    /** Tag byte indicating a {@link java.time.Instant} (0x10): an 8-byte epoch-second long followed by a 4-byte nano int. */
    public static final byte TAG_INSTANT = 0x10;
    /** Tag byte indicating an {@link java.lang.Enum} constant (0x11): declaring-class FQCN string plus its {@code name()} string. */
    public static final byte TAG_ENUM = 0x11;
    /**
     * Tag byte indicating a {@link java.util.Set} (0x12) prefixed with a 4-byte element count.
     *
     * <p>Deserialized as a {@link java.util.LinkedHashSet}, so encounter order survives the round
     * trip for ordered implementations. A {@link java.util.TreeSet} arrives as a
     * {@code LinkedHashSet} preserving the sorted order it was written in, but without its
     * {@code Comparator} — subsequent insertions on the receiving side are not re-sorted.</p>
     */
    public static final byte TAG_SET = 0x12;
    /**
     * Tag byte indicating a {@link java.math.BigDecimal} (0x13): its exact {@code toString()} form.
     *
     * <p>The string form is used rather than unscaled-value-plus-scale so precision and scale survive
     * exactly, and so the same code links under TeaVM on the client.</p>
     */
    public static final byte TAG_BIG_DECIMAL = 0x13;
    /** Tag byte indicating a {@link java.math.BigInteger} (0x14): its exact {@code toString()} form. */
    public static final byte TAG_BIG_INTEGER = 0x14;
    /** Tag byte indicating a {@link java.time.LocalDate} (0x15): an 8-byte epoch-day long. */
    public static final byte TAG_LOCAL_DATE = 0x15;
    /** Tag byte indicating a {@link java.time.LocalTime} (0x16): an 8-byte nano-of-day long. */
    public static final byte TAG_LOCAL_TIME = 0x16;
    /** Tag byte indicating a {@link java.time.LocalDateTime} (0x17): an epoch-day long then a nano-of-day long. */
    public static final byte TAG_LOCAL_DATE_TIME = 0x17;
    /** Tag byte indicating a {@link java.time.Duration} (0x18): an 8-byte seconds long then a 4-byte nano int. */
    public static final byte TAG_DURATION = 0x18;
    /**
     * Tag byte indicating a {@link java.util.Optional} (0x19): the contained value, or
     * {@link #TAG_NULL} when empty.
     *
     * <p>An {@code Optional} cannot contain null, so empty and null-content are the same state and the
     * round trip is unambiguous.</p>
     */
    public static final byte TAG_OPTIONAL = 0x19;
    /** Tag byte indicating an {@code int[]} (0x1A) prefixed with a 4-byte length. */
    public static final byte TAG_INT_ARRAY = 0x1A;
    /** Tag byte indicating a {@code long[]} (0x1B) prefixed with a 4-byte length. */
    public static final byte TAG_LONG_ARRAY = 0x1B;
    /** Tag byte indicating a {@code double[]} (0x1C) prefixed with a 4-byte length. */
    public static final byte TAG_DOUBLE_ARRAY = 0x1C;
    /** Tag byte indicating a {@code float[]} (0x1D) prefixed with a 4-byte length. */
    public static final byte TAG_FLOAT_ARRAY = 0x1D;
    /** Tag byte indicating a {@code short[]} (0x1E) prefixed with a 4-byte length. */
    public static final byte TAG_SHORT_ARRAY = 0x1E;
    /** Tag byte indicating a {@code char[]} (0x1F) prefixed with a 4-byte length. */
    public static final byte TAG_CHAR_ARRAY = 0x1F;
    /** Tag byte indicating a {@code boolean[]} (0x20) prefixed with a 4-byte length, one byte per element. */
    public static final byte TAG_BOOLEAN_ARRAY = 0x20;
    /**
     * Tag byte indicating an EclipseStore {@code Lazy} reference (0x21): a single string handle.
     *
     * <p><b>The contents are never written.</b> A lazy reference stays deferred across the network;
     * the client resolves it with an RMI round trip on first {@code get()}. Handling is delegated to
     * the tier's {@link LazyAdapter} so that this module needs no EclipseStore dependency.</p>
     */
    public static final byte TAG_LAZY = 0x21;

    private static final ThreadLocal<Set<Object>> seenObjects = ThreadLocal.withInitial(() -> Collections.newSetFromMap(new IdentityHashMap<>()));

    /**
     * Packs an object value and its type tag into the target {@link ByteBuffer}.
     *
     * @param buffer the target buffer to write binary data into
     * @param val    the value object to serialize (may be primitive wrapper, String, List, Map, byte[], or {@link BinaryPackable})
     * @param mapper the object mapper tracking reference handles
     *
     * <p><b>Under the hood:</b> Evaluates the class type of {@code val}, emits the corresponding 1-byte type tag,
     * and appends the payload. For complex objects, checks {@code seenObjects} ThreadLocal. If previously seen during
     * this call tree, writes {@link #TAG_REF} and object ID. Otherwise writes {@link #TAG_OBJECT}, object ID, FQCN,
     * and delegates field serialization to generated {@link BinarySerializerDelegate} or {@link BinaryPackable#writeToBuffer}.</p>
     */
    public static void writeValue(ByteBuffer buffer, Object val, ObjectMapper mapper) {
        if (val == null) {
            buffer.put(TAG_NULL);
        } else if (val instanceof Integer) {
            buffer.put(TAG_INT);
            buffer.putInt((Integer) val);
        } else if (val instanceof Long) {
            buffer.put(TAG_LONG);
            buffer.putLong((Long) val);
        } else if (val instanceof Double) {
            buffer.put(TAG_DOUBLE);
            buffer.putDouble((Double) val);
        } else if (val instanceof Float) {
            buffer.put(TAG_FLOAT);
            buffer.putFloat((Float) val);
        } else if (val instanceof Boolean) {
            buffer.put(TAG_BOOLEAN);
            buffer.put((byte) ((Boolean) val ? 1 : 0));
        } else if (val instanceof String) {
            buffer.put(TAG_STRING);
            writeString(buffer, (String) val);
        } else if (BinaryRegistry.getLazyAdapter() != null
                && BinaryRegistry.getLazyAdapter().isLazy(val)) {
            // Only the handle goes on the wire — resolving is the receiver's decision.
            buffer.put(TAG_LAZY);
            writeString(buffer, BinaryRegistry.getLazyAdapter().handleFor(val, mapper));
        } else if (BinaryRegistry.getDelegate(val.getClass().getName()) != null || val instanceof BinaryPackable) {
            @SuppressWarnings("unchecked")
            BinarySerializerDelegate<Object> delegate = BinaryRegistry.getDelegate(val.getClass().getName());
            Set<Object> seen = seenObjects.get();
            boolean isRoot = seen.isEmpty();
            if (seen.add(val)) {
                try {
                    String id = mapper.register(val);
                    buffer.put(TAG_OBJECT);
                    writeString(buffer, id);
                    writeString(buffer, val.getClass().getName());
                    GrowableBuffer temp = new GrowableBuffer();
                    if (delegate != null) {
                        delegate.write(val, temp, mapper);
                    } else {
                        ((BinaryPackable) val).writeToBuffer(temp, mapper);
                    }
                    buffer.put(temp.toByteArray());
                } finally {
                    if (isRoot) {
                        seen.clear();
                    }
                }
            } else {
                String id = mapper.register(val);
                buffer.put(TAG_REF);
                writeString(buffer, id);
            }
        } else if (val instanceof Short) {
            buffer.put(TAG_SHORT);
            buffer.putShort((Short) val);
        } else if (val instanceof Byte) {
            buffer.put(TAG_BYTE);
            buffer.put((Byte) val);
        } else if (val instanceof Character) {
            buffer.put(TAG_CHAR);
            buffer.putChar((Character) val);
        } else if (val instanceof UUID) {
            // TeaVM does not emulate UUID.getMostSignificantBits()/new UUID(long,long); serialize
            // via the canonical string form, which TeaVM supports, so the same code links on the
            // JVM server and the browser client.
            buffer.put(TAG_UUID);
            writeString(buffer, val.toString());
        } else if (val instanceof Instant) {
            buffer.put(TAG_INSTANT);
            Instant instant = (Instant) val;
            buffer.putLong(instant.getEpochSecond());
            buffer.putInt(instant.getNano());
        } else if (val instanceof Enum) {
            buffer.put(TAG_ENUM);
            Enum<?> constant = (Enum<?>) val;
            writeString(buffer, constant.getDeclaringClass().getName());
            writeString(buffer, constant.name());
        } else if (val instanceof List) {
            buffer.put(TAG_LIST);
            List<?> list = (List<?>) val;
            buffer.putInt(list.size());
            for (Object item : list) {
                writeValue(buffer, item, mapper);
            }
        } else if (val instanceof Set) {
            buffer.put(TAG_SET);
            Set<?> set = (Set<?>) val;
            buffer.putInt(set.size());
            for (Object item : set) {
                writeValue(buffer, item, mapper);
            }
        } else if (val instanceof Map) {
            buffer.put(TAG_MAP);
            Map<?, ?> map = (Map<?, ?>) val;
            buffer.putInt(map.size());
            for (Map.Entry<?, ?> entry : map.entrySet()) {
                writeValue(buffer, entry.getKey(), mapper);
                writeValue(buffer, entry.getValue(), mapper);
            }
        } else if (val instanceof java.math.BigDecimal) {
            buffer.put(TAG_BIG_DECIMAL);
            writeString(buffer, val.toString());
        } else if (val instanceof java.math.BigInteger) {
            buffer.put(TAG_BIG_INTEGER);
            writeString(buffer, val.toString());
        } else if (val instanceof java.time.LocalDate) {
            buffer.put(TAG_LOCAL_DATE);
            buffer.putLong(((java.time.LocalDate) val).toEpochDay());
        } else if (val instanceof java.time.LocalTime) {
            buffer.put(TAG_LOCAL_TIME);
            buffer.putLong(((java.time.LocalTime) val).toNanoOfDay());
        } else if (val instanceof java.time.LocalDateTime) {
            buffer.put(TAG_LOCAL_DATE_TIME);
            java.time.LocalDateTime dateTime = (java.time.LocalDateTime) val;
            buffer.putLong(dateTime.toLocalDate().toEpochDay());
            buffer.putLong(dateTime.toLocalTime().toNanoOfDay());
        } else if (val instanceof java.time.Duration) {
            buffer.put(TAG_DURATION);
            java.time.Duration duration = (java.time.Duration) val;
            buffer.putLong(duration.getSeconds());
            buffer.putInt(duration.getNano());
        } else if (val instanceof java.util.Optional) {
            buffer.put(TAG_OPTIONAL);
            writeValue(buffer, ((java.util.Optional<?>) val).orElse(null), mapper);
        } else if (val instanceof int[]) {
            buffer.put(TAG_INT_ARRAY);
            int[] ints = (int[]) val;
            buffer.putInt(ints.length);
            for (int item : ints) {
                buffer.putInt(item);
            }
        } else if (val instanceof long[]) {
            buffer.put(TAG_LONG_ARRAY);
            long[] longs = (long[]) val;
            buffer.putInt(longs.length);
            for (long item : longs) {
                buffer.putLong(item);
            }
        } else if (val instanceof double[]) {
            buffer.put(TAG_DOUBLE_ARRAY);
            double[] doubles = (double[]) val;
            buffer.putInt(doubles.length);
            for (double item : doubles) {
                buffer.putDouble(item);
            }
        } else if (val instanceof float[]) {
            buffer.put(TAG_FLOAT_ARRAY);
            float[] floats = (float[]) val;
            buffer.putInt(floats.length);
            for (float item : floats) {
                buffer.putFloat(item);
            }
        } else if (val instanceof short[]) {
            buffer.put(TAG_SHORT_ARRAY);
            short[] shorts = (short[]) val;
            buffer.putInt(shorts.length);
            for (short item : shorts) {
                buffer.putShort(item);
            }
        } else if (val instanceof char[]) {
            buffer.put(TAG_CHAR_ARRAY);
            char[] chars = (char[]) val;
            buffer.putInt(chars.length);
            for (char item : chars) {
                buffer.putChar(item);
            }
        } else if (val instanceof boolean[]) {
            buffer.put(TAG_BOOLEAN_ARRAY);
            boolean[] booleans = (boolean[]) val;
            buffer.putInt(booleans.length);
            for (boolean item : booleans) {
                buffer.put((byte) (item ? 1 : 0));
            }
        } else if (val instanceof byte[]) {
            buffer.put(TAG_BYTE_ARRAY);
            byte[] arr = (byte[]) val;
            buffer.putInt(arr.length);
            buffer.put(arr);
        } else {
            throw new IllegalArgumentException("Unsupported binary type tag for: " + val.getClass().getName());
        }
    }

    /**
     * Unpacks an object from the current position in the given {@link ByteBuffer}.
     *
     * @param buffer the source buffer positioned at a 1-byte type tag
     * @param mapper the object mapper to resolve or register object reference handles
     * @return the deserialized Object (primitive wrapper, String, List, Map, byte[], or domain object)
     * @throws IllegalStateException if an unmapped or invalid type tag byte is encountered
     *
     * <p><b>Under the hood:</b> Reads the tag byte via {@code buffer.get()}. Switches on tag value:
     * <ul>
     *   <li>{@link #TAG_REF}: Reads string ID, retrieves object instance from {@code mapper.getObject(id)}.</li>
     *   <li>{@link #TAG_OBJECT}: Reads object ID and class FQCN. If instance not in mapper, creates new instance via
     *       {@code BinaryRegistry.create(className)} and registers with mapper ID. Populates fields via delegate or
     *       {@link BinaryPackable#readFromBuffer}.</li>
     *   <li>Collections/Maps: Reads size int, loops and recursively calls {@code readValue}.</li>
     * </ul>
     */
    public static Object readValue(ByteBuffer buffer, ObjectMapper mapper) {
        byte tag = buffer.get();
        switch (tag) {
            case TAG_NULL:
                return null;
            case TAG_INT:
                return buffer.getInt();
            case TAG_LONG:
                return buffer.getLong();
            case TAG_DOUBLE:
                return buffer.getDouble();
            case TAG_FLOAT:
                return buffer.getFloat();
            case TAG_BOOLEAN:
                return buffer.get() != 0;
            case TAG_STRING:
                return readString(buffer);
            case TAG_REF: {
                String id = readString(buffer);
                return mapper.getObject(id);
            }
            case TAG_OBJECT:
                String id = readString(buffer);
                String className = readString(buffer);
                Object obj = mapper.getObject(id);
                boolean updatingExisting = obj != null;
                if (obj == null) {
                    obj = BinaryRegistry.create(className);
                    mapper.registerWithId(id, obj);
                }
                @SuppressWarnings("unchecked")
                BinarySerializerDelegate<Object> delegate = BinaryRegistry.getDelegate(className);
                if (delegate != null) {
                    delegate.read(obj, buffer, mapper);
                } else if (obj instanceof BinaryPackable) {
                    ((BinaryPackable) obj).readFromBuffer(buffer, mapper);
                }
                if (updatingExisting) {
                    // Fields of an instance the caller already holds were just replaced in place;
                    // anything that read them needs to re-run. A freshly created instance has no
                    // readers yet, so it is not reported.
                    LiveMutationTracker.remoteObjectUpdated(obj);
                }
                return obj;
            case TAG_SHORT:
                return buffer.getShort();
            case TAG_BYTE:
                return buffer.get();
            case TAG_CHAR:
                return buffer.getChar();
            case TAG_UUID: {
                // Matches the string-form write above (TeaVM-safe, no new UUID(long,long)).
                return UUID.fromString(readString(buffer));
            }
            case TAG_INSTANT: {
                long seconds = buffer.getLong();
                int nanos = buffer.getInt();
                return Instant.ofEpochSecond(seconds, nanos);
            }
            case TAG_ENUM: {
                String fqcn = readString(buffer);
                String name = readString(buffer);
                return name == null ? null : BinaryRegistry.resolveEnum(fqcn, name);
            }
            case TAG_LIST: {
                int size = buffer.getInt();
                List<Object> list = new ArrayList<>(size);
                for (int i = 0; i < size; i++) {
                    list.add(readValue(buffer, mapper));
                }
                return list;
            }
            case TAG_SET: {
                int size = buffer.getInt();
                Set<Object> set = new LinkedHashSet<>();
                for (int i = 0; i < size; i++) {
                    set.add(readValue(buffer, mapper));
                }
                return set;
            }
            case TAG_MAP: {
                int size = buffer.getInt();
                Map<Object, Object> map = new LinkedHashMap<>(size);
                for (int i = 0; i < size; i++) {
                    Object key = readValue(buffer, mapper);
                    Object value = readValue(buffer, mapper);
                    map.put(key, value);
                }
                return map;
            }
            case TAG_BIG_DECIMAL: {
                String text = readString(buffer);
                return text == null ? null : new java.math.BigDecimal(text);
            }
            case TAG_BIG_INTEGER: {
                String text = readString(buffer);
                return text == null ? null : new java.math.BigInteger(text);
            }
            case TAG_LOCAL_DATE:
                return java.time.LocalDate.ofEpochDay(buffer.getLong());
            case TAG_LOCAL_TIME:
                return java.time.LocalTime.ofNanoOfDay(buffer.getLong());
            case TAG_LOCAL_DATE_TIME: {
                java.time.LocalDate date = java.time.LocalDate.ofEpochDay(buffer.getLong());
                java.time.LocalTime time = java.time.LocalTime.ofNanoOfDay(buffer.getLong());
                return java.time.LocalDateTime.of(date, time);
            }
            case TAG_DURATION: {
                long seconds = buffer.getLong();
                int nanos = buffer.getInt();
                return java.time.Duration.ofSeconds(seconds, nanos);
            }
            case TAG_OPTIONAL:
                return java.util.Optional.ofNullable(readValue(buffer, mapper));
            case TAG_INT_ARRAY: {
                int len = buffer.getInt();
                int[] ints = new int[len];
                for (int i = 0; i < len; i++) {
                    ints[i] = buffer.getInt();
                }
                return ints;
            }
            case TAG_LONG_ARRAY: {
                int len = buffer.getInt();
                long[] longs = new long[len];
                for (int i = 0; i < len; i++) {
                    longs[i] = buffer.getLong();
                }
                return longs;
            }
            case TAG_DOUBLE_ARRAY: {
                int len = buffer.getInt();
                double[] doubles = new double[len];
                for (int i = 0; i < len; i++) {
                    doubles[i] = buffer.getDouble();
                }
                return doubles;
            }
            case TAG_FLOAT_ARRAY: {
                int len = buffer.getInt();
                float[] floats = new float[len];
                for (int i = 0; i < len; i++) {
                    floats[i] = buffer.getFloat();
                }
                return floats;
            }
            case TAG_SHORT_ARRAY: {
                int len = buffer.getInt();
                short[] shorts = new short[len];
                for (int i = 0; i < len; i++) {
                    shorts[i] = buffer.getShort();
                }
                return shorts;
            }
            case TAG_CHAR_ARRAY: {
                int len = buffer.getInt();
                char[] chars = new char[len];
                for (int i = 0; i < len; i++) {
                    chars[i] = buffer.getChar();
                }
                return chars;
            }
            case TAG_BOOLEAN_ARRAY: {
                int len = buffer.getInt();
                boolean[] booleans = new boolean[len];
                for (int i = 0; i < len; i++) {
                    booleans[i] = buffer.get() != 0;
                }
                return booleans;
            }
            case TAG_LAZY: {
                String handle = readString(buffer);
                LazyAdapter adapter = BinaryRegistry.getLazyAdapter();
                if (adapter == null) {
                    throw new IllegalStateException(
                            "Received a lazy reference but no LazyAdapter is installed on this tier. "
                            + "Lazy fields require zerozstack-store-eclipsestore on the server and the "
                            + "zeroz4j client runtime in the browser.");
                }
                return handle == null ? null : adapter.fromHandle(handle);
            }
            case TAG_BYTE_ARRAY: {
                int len = buffer.getInt();
                byte[] arr = new byte[len];
                buffer.get(arr);
                return arr;
            }
            default:
                throw new IllegalStateException("Unknown type tag in binary stream: " + tag);
        }
    }

    /**
     * Writes a UTF-8 string to the buffer, prefixed by its length in bytes.
     *
     * @param buffer the destination buffer
     * @param str    the string to write (writes -1 integer length if null)
     *
     * <p><b>Under the hood:</b> Encodes string using {@link StandardCharsets#UTF_8}. Writes 4-byte length header followed
     * by raw UTF-8 byte payload into {@code buffer}.</p>
     */
    public static void writeString(ByteBuffer buffer, String str) {
        if (str == null) {
            buffer.putInt(-1);
        } else {
            byte[] bytes = str.getBytes(StandardCharsets.UTF_8);
            buffer.putInt(bytes.length);
            buffer.put(bytes);
        }
    }

    /**
     * Reads a UTF-8 string from the buffer, prefixed by its 4-byte length.
     *
     * @param buffer the source buffer
     * @return decoded String, or {@code null} if the length header is -1
     *
     * <p><b>Under the hood:</b> Reads 4-byte length integer via {@code buffer.getInt()}. Allocates byte array of size,
     * reads bytes via {@code buffer.get(bytes)}, and constructs new String using UTF-8 charset.</p>
     */
    public static String readString(ByteBuffer buffer) {
        int len = buffer.getInt();
        if (len == -1) {
            return null;
        }
        byte[] bytes = new byte[len];
        buffer.get(bytes);
        return new String(bytes, StandardCharsets.UTF_8);
    }

    /**
     * Packs an object value and its type tag into a {@link GrowableBuffer}.
     *
     * @param buffer the growable buffer to write to
     * @param val    the value to serialize
     * @param mapper the object mapper tracking reference handles
     *
     * <p><b>Under the hood:</b> Mirror implementation of {@link #writeValue(ByteBuffer, Object, ObjectMapper)}
     * optimized for writing into expanding {@link GrowableBuffer} without requiring explicit pre-allocation.</p>
     */
    public static void writeValue(GrowableBuffer buffer, Object val, ObjectMapper mapper) {
        if (val == null) {
            buffer.put(TAG_NULL);
        } else if (val instanceof Integer) {
            buffer.put(TAG_INT);
            buffer.putInt((Integer) val);
        } else if (val instanceof Long) {
            buffer.put(TAG_LONG);
            buffer.putLong((Long) val);
        } else if (val instanceof Double) {
            buffer.put(TAG_DOUBLE);
            buffer.putDouble((Double) val);
        } else if (val instanceof Float) {
            buffer.put(TAG_FLOAT);
            buffer.putFloat((Float) val);
        } else if (val instanceof Boolean) {
            buffer.put(TAG_BOOLEAN);
            buffer.put((byte) ((Boolean) val ? 1 : 0));
        } else if (val instanceof String) {
            buffer.put(TAG_STRING);
            writeString(buffer, (String) val);
        } else if (BinaryRegistry.getLazyAdapter() != null
                && BinaryRegistry.getLazyAdapter().isLazy(val)) {
            // Only the handle goes on the wire — resolving is the receiver's decision.
            buffer.put(TAG_LAZY);
            writeString(buffer, BinaryRegistry.getLazyAdapter().handleFor(val, mapper));
        } else if (BinaryRegistry.getDelegate(val.getClass().getName()) != null || val instanceof BinaryPackable) {
            @SuppressWarnings("unchecked")
            BinarySerializerDelegate<Object> delegate = BinaryRegistry.getDelegate(val.getClass().getName());
            Set<Object> seen = seenObjects.get();
            boolean isRoot = seen.isEmpty();
            if (seen.add(val)) {
                try {
                    String id = mapper.register(val);
                    buffer.put(TAG_OBJECT);
                    writeString(buffer, id);
                    writeString(buffer, val.getClass().getName());
                    
                    if (delegate != null) {
                        delegate.write(val, buffer, mapper);
                    } else {
                        ((BinaryPackable) val).writeToBuffer(buffer, mapper);
                    }
                } finally {
                    if (isRoot) {
                        seen.clear();
                    }
                }
            } else {
                String id = mapper.register(val);
                buffer.put(TAG_REF);
                writeString(buffer, id);
            }
        } else if (val instanceof Short) {
            buffer.put(TAG_SHORT);
            buffer.putShort((Short) val);
        } else if (val instanceof Byte) {
            buffer.put(TAG_BYTE);
            buffer.put((Byte) val);
        } else if (val instanceof Character) {
            buffer.put(TAG_CHAR);
            buffer.putChar((Character) val);
        } else if (val instanceof UUID) {
            // TeaVM does not emulate UUID.getMostSignificantBits()/new UUID(long,long); serialize
            // via the canonical string form, which TeaVM supports, so the same code links on the
            // JVM server and the browser client.
            buffer.put(TAG_UUID);
            writeString(buffer, val.toString());
        } else if (val instanceof Instant) {
            buffer.put(TAG_INSTANT);
            Instant instant = (Instant) val;
            buffer.putLong(instant.getEpochSecond());
            buffer.putInt(instant.getNano());
        } else if (val instanceof Enum) {
            buffer.put(TAG_ENUM);
            Enum<?> constant = (Enum<?>) val;
            writeString(buffer, constant.getDeclaringClass().getName());
            writeString(buffer, constant.name());
        } else if (val instanceof List) {
            buffer.put(TAG_LIST);
            List<?> list = (List<?>) val;
            buffer.putInt(list.size());
            for (Object item : list) {
                writeValue(buffer, item, mapper);
            }
        } else if (val instanceof Set) {
            buffer.put(TAG_SET);
            Set<?> set = (Set<?>) val;
            buffer.putInt(set.size());
            for (Object item : set) {
                writeValue(buffer, item, mapper);
            }
        } else if (val instanceof Map) {
            buffer.put(TAG_MAP);
            Map<?, ?> map = (Map<?, ?>) val;
            buffer.putInt(map.size());
            for (Map.Entry<?, ?> entry : map.entrySet()) {
                writeValue(buffer, entry.getKey(), mapper);
                writeValue(buffer, entry.getValue(), mapper);
            }
        } else if (val instanceof java.math.BigDecimal) {
            buffer.put(TAG_BIG_DECIMAL);
            writeString(buffer, val.toString());
        } else if (val instanceof java.math.BigInteger) {
            buffer.put(TAG_BIG_INTEGER);
            writeString(buffer, val.toString());
        } else if (val instanceof java.time.LocalDate) {
            buffer.put(TAG_LOCAL_DATE);
            buffer.putLong(((java.time.LocalDate) val).toEpochDay());
        } else if (val instanceof java.time.LocalTime) {
            buffer.put(TAG_LOCAL_TIME);
            buffer.putLong(((java.time.LocalTime) val).toNanoOfDay());
        } else if (val instanceof java.time.LocalDateTime) {
            buffer.put(TAG_LOCAL_DATE_TIME);
            java.time.LocalDateTime dateTime = (java.time.LocalDateTime) val;
            buffer.putLong(dateTime.toLocalDate().toEpochDay());
            buffer.putLong(dateTime.toLocalTime().toNanoOfDay());
        } else if (val instanceof java.time.Duration) {
            buffer.put(TAG_DURATION);
            java.time.Duration duration = (java.time.Duration) val;
            buffer.putLong(duration.getSeconds());
            buffer.putInt(duration.getNano());
        } else if (val instanceof java.util.Optional) {
            buffer.put(TAG_OPTIONAL);
            writeValue(buffer, ((java.util.Optional<?>) val).orElse(null), mapper);
        } else if (val instanceof int[]) {
            buffer.put(TAG_INT_ARRAY);
            int[] ints = (int[]) val;
            buffer.putInt(ints.length);
            for (int item : ints) {
                buffer.putInt(item);
            }
        } else if (val instanceof long[]) {
            buffer.put(TAG_LONG_ARRAY);
            long[] longs = (long[]) val;
            buffer.putInt(longs.length);
            for (long item : longs) {
                buffer.putLong(item);
            }
        } else if (val instanceof double[]) {
            buffer.put(TAG_DOUBLE_ARRAY);
            double[] doubles = (double[]) val;
            buffer.putInt(doubles.length);
            for (double item : doubles) {
                buffer.putDouble(item);
            }
        } else if (val instanceof float[]) {
            buffer.put(TAG_FLOAT_ARRAY);
            float[] floats = (float[]) val;
            buffer.putInt(floats.length);
            for (float item : floats) {
                buffer.putFloat(item);
            }
        } else if (val instanceof short[]) {
            buffer.put(TAG_SHORT_ARRAY);
            short[] shorts = (short[]) val;
            buffer.putInt(shorts.length);
            for (short item : shorts) {
                buffer.putShort(item);
            }
        } else if (val instanceof char[]) {
            buffer.put(TAG_CHAR_ARRAY);
            char[] chars = (char[]) val;
            buffer.putInt(chars.length);
            for (char item : chars) {
                buffer.putChar(item);
            }
        } else if (val instanceof boolean[]) {
            buffer.put(TAG_BOOLEAN_ARRAY);
            boolean[] booleans = (boolean[]) val;
            buffer.putInt(booleans.length);
            for (boolean item : booleans) {
                buffer.put((byte) (item ? 1 : 0));
            }
        } else if (val instanceof byte[]) {
            buffer.put(TAG_BYTE_ARRAY);
            byte[] arr = (byte[]) val;
            buffer.putInt(arr.length);
            buffer.put(arr);
        } else {
            throw new IllegalArgumentException("Unsupported type for GrowableBuffer: " + val.getClass().getName());
        }
    }

    /**
     * Writes a UTF-8 string to a {@link GrowableBuffer}, prefixed by its length.
     *
     * @param buffer the destination growable buffer
     * @param str    the string to write (may be null)
     *
     * <p><b>Under the hood:</b> Writes 4-byte length integer into {@code buffer}, then writes UTF-8 encoded string bytes.</p>
     */
    public static void writeString(GrowableBuffer buffer, String str) {
        if (str == null) {
            buffer.putInt(-1);
        } else {
            byte[] bytes = str.getBytes(StandardCharsets.UTF_8);
            buffer.putInt(bytes.length);
            buffer.put(bytes);
        }
    }
}
